### ISSUE TITLE
[Bug]: Directory Separator issue on Windows

### ISSUE THREAD

**Issue by creode-dev** [creode-modules/laravel-assets#4]
### What happened?

When running tests on Windows machines, the path functionality has an issue on windows relating to the directory separator.

### How to reproduce the bug

Running tests on Github Actions.

### Package Version

1.1.0

### PHP Version

8.1.0

### Laravel Version

10.0

### Which operating systems does with happen with?

Windows

**Comment by jaymeh** [comment]
Resolved with Merge Request linked above
